<?php

namespace Acme\SearchBundle\Repository;

use Acme\SearchBundle\Entity\SearchIndexItem;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping;


/**
 * SearchIndexItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchIndexItemRepository extends EntityRepository
{

    /**
     * Construct
     */

    public function __construct(EntityManager $em, Mapping\ClassMetadata $class)
    {
        parent::__construct($em, $class);
    }


    /**
     * Build searchEntityItem from arguments
     * @param string $content
     * @param int $entityId
     * @param string $entityType
     * @return SearchIndexItem
     */
    public function buildSearchIndexItem(string $content, int $entityId, string $entityType)
    {
        $e = new SearchIndexItem();
        $e->setContent($content);
        $e->setEntityId($entityId);
        $e->setEntityType($entityType);
        return $e;
    }
}
