services:
  find-item-command:
    class: Acme\SearchBundle\Command\SearchIndexForItemCommand
    arguments:
      - "@search-index-item-repository"
    tags:
      -
        name: "console.command"

  search-index-item-metadata:
    class: Doctrine\ORM\Mapping\ClassMetadata
    arguments:
      - "Acme\\SearchBundle\\Entity\\SearchIndexItem"

  search-index-item-repository:
    class: Acme\SearchBundle\Repository\SearchIndexItemRepository
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@search-index-item-metadata"





#    acme_search.example:
#        class: Acme\SearchBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
